name: Daily Web3 Scraper

on:
  workflow_dispatch: # this enables manual run. 
  schedule:
    - cron: "0 2 * * *"
  # push:
  #   branches:
  #     - main
  #     - 'releases/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Clone pythonmodules repository
      run: |
        git clone --depth=1 https://${{ secrets.CUSTOM_TOKEN }}@github.com/liqtags/pythonmodules pythonmodules
        cd pythonmodules
        python setup.py install
    - name: Run Scraper
      run: |
        python scrape.py
    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "liqtags"
        git config --global user.email "13621351+liqtags@users.noreply.github.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push